### ISSUE TITLE
Окно формы добавления новых объектов до вызова этой формы

### ISSUE THREAD

**Issue by Stedis23** [doublezzzzzzzz/weapon#1]
Шаги для получения проблемы:
1. Запустить проект

Что ожидается? Что получили в итоге? 
Ожидалось, что форма добавления новых объектов будет открываться при ее вызове на главной форме с помощью кнопки  "add". Получили, что форма всплывает сразу при запуске приложения.

![image](https://github.com/doublezzzzzzzz/weapon/assets/142211792/84ea0580-bd94-43f5-9da1-a05ce4a5b2ee)

**Comment by doublezzzzzzzz** [comment]
При запуске программы, в методах form1 сразу происходил вызов кнопки, отвечающий за вызов form2. Исключив этот момент, мы исправили баг

![image](https://github.com/doublezzzzzzzz/weapon/assets/140835071/a401f5f8-3ce7-442c-ac33-94487d97c3f8)
